# Generated by Django 3.2.11 on 2022-01-09 15:11

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_authorindexpage_authorpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='content.AuthorPage'),
        ),
    ]
